# Generated by Django 4.2.7 on 2025-09-18 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagrama',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Nuevo Diagrama', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diagrams',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EntidadClase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='diagrams.diagrama')),
            ],
            options={
                'db_table': 'class_entities',
                'unique_together': {('diagram', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('association', 'Association'), ('inheritance', 'Inheritance'), ('composition', 'Composition'), ('aggregation', 'Aggregation')], default='association', max_length=20)),
                ('cardinality_from', models.CharField(default='1', max_length=10)),
                ('cardinality_to', models.CharField(default='1', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='diagrams.diagrama')),
                ('from_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='diagrams.entidadclase')),
                ('to_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='diagrams.entidadclase')),
            ],
            options={
                'db_table': 'relationships',
                'unique_together': {('from_class', 'to_class', 'relationship_type')},
            },
        ),
        migrations.CreateModel(
            name='AtributoClase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(default='String', max_length=50)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('protected', 'Protected')], default='public', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='diagrams.entidadclase')),
            ],
            options={
                'db_table': 'class_attributes',
                'unique_together': {('class_entity', 'name')},
            },
        ),
    ]
