# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - diagram-class-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      # Aquí podrías agregar pruebas: python manage.py test

      - name: Generate build artifact (backend only)
        run: |
          mkdir -p artifact
          cp -R backend/* artifact/
          chmod +x artifact/startup.sh || true
          # Remover entornos virtuales si existieran
          rm -rf artifact/venv || true
          rm -rf artifact/.venv || true

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: backend-package
          path: artifact

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-package

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BBF48D167B184163BEC9FEAB65EC87D6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0FC58018344C427D8FC14D9F16B06C54 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B8BDEDB9405341D2B28D5BDBD9D54384 }}

      - name: Deploy to Azure Web App (Procfile + Daphne)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'diagram-class-backend'
          slot-name: 'Production'
          package: '.'

      - name: Show deployed files list (debug)
        run: |
          echo "Listing top-level deployed files:" || true
          ls -1
          